### ISSUE TITLE
[FEATURE] CreateIngestPipelineStep Improvements

### ISSUE THREAD

**Issue by joshpalis** [opensearch-project/flow-framework#104]
### Is your feature request related to a problem?
In an effort to address any issues/gaps with the current step implementations, this issue is to track necessary modifications for the `CreateIngestPipelineStep`.

- [ ] The use case template workflow parser is responsible for populating the `WorkflowData` that each `WorkflowStep` will read information from to execute their function. Modify how the `CreateIngestPipelineStep` currently reads data from the `WorkflowData` to ensure that the expected information is read correctly. The following example `WorkflowData` is what is generated from the following use case template section.

Use Case Template Create Ingest Pipeline Section : 
```
{
    "id": "create_ingest_pipeline",
    "type": "create_ingest_pipeline",
    "inputs": {
      "id": "my-ingest-pipeline",
      "description": "some description",
      "processors": [
        {
          "type": "text_embedding",
          "params": {
            "model_id": "my-existing-model-id",
            "input_field_name": "text_passage",
            "output_field_name": "text_embedding"
          }
        }
      ]
    }
  }
```

WorkflowData :
```
{
    description=some description,
    id=my-ingest-pipeline, 
    processors=[Lorg.opensearch.flowframework.model.PipelineProcessor;
}
```

Note : The `PipelineProcessor` ([link](https://github.com/opensearch-project/opensearch-ai-flow-framework/blob/63ef780ba6bd9edd6286b38020e2a34956ab5c1f/src/main/java/org/opensearch/flowframework/model/PipelineProcessor.java)) contains the type and a list of required parameters for this type. In the case of the `text-embedding` processor, the required parameters are the `model_id`, 'input_field_name', 'output_field_name'.

**Comment by amitgalitz** [comment]
Done with https://github.com/opensearch-project/flow-framework/pull/558
