### ISSUE TITLE
[FEATURE] Enhance update workflow API to allow update on provisioned workflow

### ISSUE THREAD

**Issue by amitgalitz** [opensearch-project/flow-framework#122]
### Is your feature request related to a problem?
Coming from [here](https://github.com/opensearch-project/opensearch-ai-flow-framework/pull/110#discussion_r1375118772).

Currently we have a basic update functionality where we update the entire doc in the global-context index and workflow-state index whenever an update is made. However this doesn't take into account a few things. If we are updating while provisioning is going on we will have to potentially rollback the current steps that were executed. Another caveat is that if provisioning is already done, and users just want to update the query flow for example we probably don't want to create a whole new doc and rollback. 

Update failures also are currently a little tricky right now.  If we fail to update the state doc for whatever reason, the information regarding provisioning time and more could be wrong here but the global context doc will be updates causes the two not to be synced. In AD when we update a detector for example we need to stop the task beforehand anyways for example so the task is anyways gone before we update. Maybe we should do something similar for us too where we stop the workflow before updating and then that means we either reset or state document there or we delete it completely. When we update and restart the workflow we can create a new state document after handling any failures in stopping.

### What solution would you like?

t?

**Comment by owaiskazi19** [comment]
@amitgalitz can you verify if this is addressed in https://github.com/opensearch-project/flow-framework/pull/416?

**Comment by amitgalitz** [comment]
> @amitgalitz can you verify if this is addressed in #416?

#416 addresses some of the issue by only allowing updates on non-provisioned workflows. However I think we should continue to aim for an update API that can do more than then. Not sure if 2.13 or even later. Think its still good to call this out as future enhancement, I will update title to reflect that unless you think what we have is good enough for long term.

**Comment by minalsha** [comment]
Will be addressed with issue: #526
