### ISSUE TITLE
[FEATURE] Check the plugins installed before running provisioning

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/flow-framework#126]
### Is your feature request related to a problem?
Coming from 2nd task of https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/108. 

Provision API runs a workflow Step which is nothing but a building block for a specific plugin. To execute the APIs of that plugin, it needs to be installed in the OS cluster or else flow framework plugin won't be able to do provisioning. We can't add all the plugins in `extendedPlugins`, that will create dependency on all the plugins even if their APIs are not required in any workflow step of the template.

### What solution would you like?
There should be a mechanism to check the list of plugins installed and template should have a field called as `plugins` consisting of list of plugins required for a specific workflow. The first template validation should be to check if the plugins mentioned in the template are installed in the OS cluster.

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by dbwiddis** [comment]
My preferred implementation:  
1. add a field "required_plugins" (String array) to the workflow step JSON [here](https://github.com/opensearch-project/opensearch-ai-flow-framework/blob/main/src/main/resources/mappings/workflow-steps.json).
2. when validating a plugin, iterate the steps (which we are already doing for validating input/output) and collect the strings from this entry, adding them to a `Set` as we go along
3. take this set and compare it to the list of installed plugins.  See [sample code here](https://github.com/opensearch-project/opensearch-ai-flow-framework/blob/ac76a44927a6e475694f563b2a033aaa498d13e8/src/test/java/org/opensearch/flowframework/FlowFrameworkPluginIT.java#L22-L29) for obtaining installed plugins.

**Comment by joshpalis** [comment]
Closed by https://github.com/opensearch-project/flow-framework/pull/290
