### ISSUE TITLE
[FEATURE] Set up CI to track ml-commons agent_framework feature branch

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/flow-framework#138]
### Is your feature request related to a problem?

The various feature branches in ml-commons will eventually be merged into the `agent_framework` branch.  We should set up our CI to track that branch.

### What solution would you like?

CI needs to publish to maven local for the ml-commons dependency.

### Do you have any additional context?

We can keep our dependency on ML commons 2.x until this branch is ready; and we need to make sure appropriate PRs get backported into that branch.

**Comment by owaiskazi19** [comment]
@dbwiddis there are 2 branches `agent_framework` and `agent_framework_dev` which should we run CI on?
