### ISSUE TITLE
[BUG] Workflow Parsing fails with another Map Object

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/flow-framework#157]
### What is the bug?
With the new addition to Template Model, UI_METADATA field. The parser for workflow treats ui_metdata field as another workflow item.

https://github.com/opensearch-project/opensearch-ai-flow-framework/blob/1de0ca54ab29c00987f56e982c87855b70e47911/src/main/java/org/opensearch/flowframework/model/Template.java#L164-L169
### How can one reproduce the bug?
_Steps to reproduce the behavior._

1. Add a new map object similar to https://github.com/opensearch-project/opensearch-ai-flow-framework/pull/156 and run tests.
```
REPRODUCE WITH: ./gradlew ':test' --tests "org.opensearch.flowframework.model.TemplateTests.testTemplate" -Dtests.seed=11B7CC6871F9718B -Dtests.security.manager=false -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=th-TH-u-nu-thai-x-lvariant-TH -Dtests.timezone=Pacific/Samoa -Druntime.java=14

org.opensearch.flowframework.model.TemplateTests > testTemplate FAILED
    java.io.IOException: A workflow must have at least one node.
        at __randomizedtesting.SeedInfo.seed([11B7CC6871F9718B:5B2B768F27CFA470]:0)
        at org.opensearch.flowframework.model.Workflow.parse(Workflow.java:120)
        at org.opensearch.flowframework.model.Template.parse(Template.java:299)
        at org.opensearch.flowframework.model.Template.parse(Template.java:341)
        at org.opensearch.flowframework.model.TemplateTests.testTemplate(TemplateTests.java:63)

```

### What is the expected behavior?
Parsing should pass

### What is your host/environment?
MacOS

### Do you have any screenshots?
![Screenshot 2023-11-09 at 11 26 06 AM](https://github.com/opensearch-project/opensearch-ai-flow-framework/assets/16099877/6ecc196e-10d5-49fc-b5b3-ff7016cb20e4)

### Do you have any additional context?
_Add any other context about the problem._

**Comment by dbwiddis** [comment]
Is this still an issue or can it be closed?

**Comment by minalsha** [comment]
@owaiskazi19  does this issue still persists?
