### ISSUE TITLE
[PROPOSAL] Rename repo to flow-framework

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/flow-framework#168]
### What are you proposing?
Based on https://github.com/opensearch-project/opensearch-plugins/blob/main/CONVENTIONS.md#plugin-naming-conventions we should not have a repo name starting with `opensearch`. That makes our repo name to `ai-flow-framework`. 
The use cases for the plugin in the future would not be just "AI" focused and can range from cluster management to resource management. That removes the "ai" keyword from the repo name and finally makes it `flow-framework`.

**Comment by owaiskazi19** [comment]
@opensearch-project/admin can you please help with this issue?

**Comment by peternied** [comment]
_Same comment as the frontend plugin_

Renaming the repository is a one-way-door kind of change - @ohltyler could you see about getting 'lazy consensus' [1] on what the name is?  With that change agreed on you might want to reach out to #admin-requests channel if you need traction.

- [1] https://www.apache.org/foundation/how-it-works/#decision-making

**Comment by ohltyler** [comment]
We have gotten approval from @opensearch-project/admin to go ahead with the name change - this simply aligns the name with the proposed naming conventions already outlined, and has a small blast radius as it isn't onboarded into the OpenSearch build ecosystem yet.
