### ISSUE TITLE
[BUG] Validate that all step IDs are unique

### ISSUE THREAD

**Issue by amitgalitz** [opensearch-project/flow-framework#189]
### What is the bug?
Currently we are allowed to create a template where we have duplicate step IDs throughout the steps. It would be beneficial to ensure these step IDs are unique so they can be used to identify different steps, especially in the resources created section.

This can be crucial for users wanting to know which step they listed corresponds to the created resource id.

### Solution:

We can add validation to make sure all step_id's are unique, this can be done by adding the step_id to a set and make sure we don't have duplicates.

**Comment by dbwiddis** [comment]
The topological sorter uses a map internally when sorting the nodes:
https://github.com/opensearch-project/flow-framework/blob/0edf9cb512a1bdb338d01d4340c6831547066345/src/main/java/org/opensearch/flowframework/workflow/WorkflowProcessSorter.java#L71

So while there is a bug, it's far worse than just the resources created. It totally messes up the logic of the sorting, combining edges and other nastiness.

Easy fix is to check if the key exists here before putting in the map.
https://github.com/opensearch-project/flow-framework/blob/0edf9cb512a1bdb338d01d4340c6831547066345/src/main/java/org/opensearch/flowframework/workflow/WorkflowProcessSorter.java#L92

**Comment by dbwiddis** [comment]
Actually, that won't work, the ids are already unique in the topological sorting from here:
https://github.com/opensearch-project/flow-framework/blob/0edf9cb512a1bdb338d01d4340c6831547066345/src/main/java/org/opensearch/flowframework/workflow/WorkflowProcessSorter.java#L161

So the fix is to compare the size of that set to the size of `workflowNodes`.
