### ISSUE TITLE
[BUG] WorkflowNode Parsing Fails for type Instant and Nested Objects

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/flow-framework#196]
### What is the bug?
For the request like:
```json
"llm": {
              "model_id": "ldzS04kBxRPZ5cnWrqpd",
              "parameters": {
                  "type": "hello"
              }
          }
```
the parsing for WorkflowNode fails with the below
```
{
    "error": "Can't get text on a START_OBJECT at 56:43"
}
```

and for the fieldsof type Instant 

```
created_time: 12684646585
```
fails with the below
```
Current token (FIELD_NAME) not numeric, can not use numeric value accessors
```

### How can one reproduce the bug?
1. Pass a nested object to the Create API to reproduce the first bug.
2. pass an instant value to the Create API to reproduce the second one.

### What is the expected behavior?
Parsing should go through.

### What is your host/environment?
Ubuntu

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by dbwiddis** [comment]
The nested maps was an intentional thing to stop infinite recursion. You need to encode "parameters" as a special case like this:

https://github.com/opensearch-project/flow-framework/blob/10923251c59841d5f35fa7a588780495434f0768/src/main/java/org/opensearch/flowframework/model/WorkflowNode.java#L147-L153

(But probably under `START_OBJECT` rather than the array)

**Comment by dbwiddis** [comment]
> Current token (FIELD_NAME) not numeric, can not use numeric value accessors

Where are you trying to parse an `Instant`?  You're trying to parse the field name not value here.

**Comment by owaiskazi19** [comment]
> > Current token (FIELD_NAME) not numeric, can not use numeric value accessors
> 
> Where are you trying to parse an `Instant`? You're trying to parse the field name not value here.

Pasted the wrong error message here but basically needed to add parsing for numbers. Handled both the cases in this PR: https://github.com/opensearch-project/flow-framework/pull/198
