### ISSUE TITLE
[FEATURE] Create and provision workflow in the same time

### ISSUE THREAD

**Issue by amitgalitz** [opensearch-project/flow-framework#280]
### Is your feature request related to a problem?

Currently in order to provision a workflow, you first have to create the workflow and receive a workflowId. 

```
/_plugins/_flow_framework/workflow
{}
response:
workflowId: "G513W4wBRItvelfmy_w4"
/_plugins/_flow_framework/workflow/G513W4wBRItvelfmy_w4/_provision
response:
workflowId: "G513W4wBRItvelfmy_w4"
```

### What solution would you like?
We should have the option to add an optional `provision=true` flag to the create API to start provisioning right after create:

`/_plugins/_flow_framework/workflow?provision=true`

**Comment by dbwiddis** [comment]
This duplicates #259

**Comment by amitgalitz** [comment]
> This duplicates #259

didn't notice we had this already, closing this one
