### ISSUE TITLE
[DISCUSS] Open Questions for docs / APIs

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/flow-framework#315]
While drafting the API documentation (#311) I encountered a few questions that I need team feedback on.

1. Is `use_case` an enum or user-defined field?  I think we originally identified it as an enum for use by the front-end.  Whatever it is, we need to add code for it and document it.
   - I've inserted some words to this effect.
2. I need to add params to the documentation. 
   - I've done this
3. I think given our limited number of steps for 2.12 the "Sample Workflow Steps" (#314) may be sufficient for workflow step documentation.  But we really need to improve that in later releases. Open to thoughts on:
   - Do we need individual API docs for each workflow step or can we just reference ML Commons API, or some mix?
      - I've linked to individual APIs for all cases and documented differences
   - Do we need an API that returns all the workflow steps and required/optional inputs (essentially the [content of this json file](https://github.com/opensearch-project/flow-framework/blob/main/src/main/resources/mappings/workflow-steps.json) as an API)?
      - I think we do
      - https://github.com/opensearch-project/flow-framework/issues/364

**Comment by amitgalitz** [comment]
I think `use_case` should be an enum based on pre-defined cases, we still don't really have those yet though I think.

I think we can add links to the API that the steps will be using
