### ISSUE TITLE
[FEATURE] Overhaul WORKFLOW_REQUEST_TIMEOUT setting

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/flow-framework#330]
Coming from https://github.com/opensearch-project/flow-framework/pull/317#discussion_r1437288166

### Is your feature request related to a problem?

We have a setting `WORKFLOW_REQUEST_TIMEOUT` whose only purpose is to provide a timeout for the Create/Update API.  This is someone redundant as there is already a systemwide OpenSearch REST timeout setting, and our create/provision APIs aren't expected to take more than a few hundred milliseconds.

We also have configurable step timeouts, a per-step timeout just implemented in #317 that we control in our workflow-steps.json file, and a per-step timeout override that users may provide with a `node_timeout` setting in their `user_inputs` section.  However, the default if neither of those is specified is hard-coded.

### What solution would you like?

Change the `WORKFLOW_REQUEST_TIMEOUT` to `WORKFLOW_STEP_DEFAULT_TIMEOUT` and use it as the fallback that is currently hardcoded.

### What alternatives have you considered?

Leaving things as they are and documenting a hardcoded value that we could easily configure.   

Adding another timeout setting and documenting why we have a separate one for a call that always returns immediately anyway.

### Do you have any additional context?

![image](https://github.com/opensearch-project/flow-framework/assets/9291703/5f464017-fba1-4e51-b90d-7dd3583b9645)

**Comment by amitgalitz** [comment]
> and our create/provision APIs aren't expected to take more than a few hundred milliseconds.

There could be cases where our provision takes longer, and some of the reason why we are doing this async no?

Did you mean this time out is only on create and not on provision? Create should be fast and provision could be slow, and if we guarantee its not slow then it should maybe be moved to sync.

I think its okay though to leave as is and have a step time out and a total API timeout? However for sync requests timeout are more important (create/update). For async requests (provision) we can still have a total timeout but should definitely be longer. 

Step timeout can be more important for steps users knows will take longer?

**Comment by dbwiddis** [comment]
> There could be cases where our provision takes longer,

Yes, but our API returns the workflow ID immediately, even while provisioning is in progress, and thus will never hit this feature.

I'm just going to remove this setting entirely.

**Comment by dbwiddis** [comment]
After going through the removal process I realized this setting applied only to a search request performed internally for the max workflows, which needs a default timeout.  So I extended it to cover our other search (workflow/state) use cases as well, and refactored to avoid having to pass it around in the workflow request.

**Comment by amitgalitz** [comment]
> After going through the removal process I realized this setting applied only to a search request performed internally for the max workflows, which needs a default timeout. So I extended it to cover our other search (workflow/state) use cases as well, and refactored to avoid having to pass it around in the workflow request.

Do you mean that we will keep the timeout variable and use it for search unrelated to the the other issue with the timeout for each step?

**Comment by dbwiddis** [comment]
> Do you mean that we will keep the timeout variable and use it for search unrelated to the the other issue with the timeout for each step?

This is unrelated to "step timeout".

This is associated with REST request timeout when there is a search involved, specifically:
 - the search for number of workflows for the max workflow check
 - the search for workflows, or the search for workflow state in those APIs
