### ISSUE TITLE
[FEATURE] Replace/augment MAX_GET_TASK_REQUEST_RETRY with a calculation based on timeout

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/flow-framework#338]
### Is your feature request related to a problem?

The retryable workflow step abstract class relies on a constant number of retries, `MAX_GET_TASK_REQUEST_RETRY`.  This isn't very useful for two reasons:
 - it might timeout long before the user's specified timeout and then do nothing
 - if it retries past the timeout, it'll just get cancelled, and may as well not exist

Any timeout setting should have some reference to the step's timeout.

### What solution would you like?

Pick one:
 - Keep the `MAX_GET_TASK_REQUEST_RETRY` setting as is, but calculate the delay between retries based on the step timeout
 - Replace `MAX_GET_TASK_REQUEST_RETRY` with a duration between retries setting and calculate retries based on the step timeout and that duration
 - Eliminate `MAX_GET_TASK_REQUEST_RETRY` and just retry at a fixed duration (possibly set by the user) until the timeout
 - Some other idea I haven't thought of

**Comment by joshpalis** [comment]
> Keep the MAX_GET_TASK_REQUEST_RETRY setting as is, but calculate the delay between retries based on the step timeout

+1 to this approach, but open to option 2 (perhaps I just need more information on the effective difference between the two to make a final decision)

**Comment by dbwiddis** [comment]
> I just need more information on the effective difference between the two to make a final decision

Assume a timeout of 15s.

Option 1 (Keep) means for a max of 5 retries, we'd retry every 3 seconds.
    - I don't personally like this because if someone wants to set a 20 minute timeout and leaves retries at 5, that's 4 minutes between retries.  That's unexpected.  I'd prefer to get rid of RETRY and choose one of the next 2 options

Option 2 (Replace) means instead of a MAX RETRY setting we'd have a RETRY DELAY setting specifying how frequently to retry, and do so until we timeout.   We would calculate the # of retries internally so the code would stay mostly the same.

Option 3 is similar to option 2 without any calculation, so the loop would just go indefinitely (until cancelled).  Effectively the same thing as option 2, just an implementation detail.

**Comment by amitgalitz** [comment]
I don't have too strong of an opinion against any of the option but to me option 2/3 makes sense.

However for your comment on option 1: "if someone wants to set a 20 minute timeout and leaves retries at 5, that's 4 minutes between retries. That's unexpected."

I don't know if I agree that its unexpected but it might just mean they are waiting way longer then they need too. 

We can have a variable that defines the time between between retries that is set to some default number, users could change this if they want but could easily ignore this. This default could be 10 seconds and then we just retry every 10 seconds until we hit total timeout of that was set or it succeeds.
