### ISSUE TITLE
[CI] Add at least one multi-node integ test

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/flow-framework#354]
### Is your feature request related to a problem?

Our integration tests only run on a single node cluster, as noted [here](https://github.com/opensearch-project/flow-framework/pull/353#issuecomment-1876045331).

### What solution would you like?

At least one integ test should run on multi-node cluster.

**Comment by owaiskazi19** [comment]
https://github.com/opensearch-project/flow-framework/pull/416 addresses the issue.
