### ISSUE TITLE
[DISCUSS] Provide sample template to users without needing docs

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/flow-framework#356]
### Is your feature request related to a problem?

Customers would like to use a sample template without copying and pasting from documentation.

### What solution would you like?

There are many alternatives. We should decide on one that will support front end search/integration.
 - REST API (list / query sample templates)?
 - Folder on the class path?
 - A better idea?

**Comment by joshpalis** [comment]
We have some sample templates [here](https://github.com/opensearch-project/flow-framework/tree/main/src/test/resources/template) that we use for integration testing. Would this be sufficient?
