### ISSUE TITLE
[FEATURE] Separate Local Model Registration to support Custom, Pretrained and Sparse Encoding Models

### ISSUE THREAD

**Issue by joshpalis** [opensearch-project/flow-framework#377]
### Is your feature request related to a problem?
Coming from flaky integration test failures due to the memory limitations of Github action runners which facilitate integration tests ([Reference](https://github.com/opensearch-project/flow-framework/actions/runs/7427053910/job/20212796098?pr=374)), it has been determined that mitigation would require using a smaller model to test out local model registration within an integration test cluster. 

The `amazon/neural-sparse/opensearch-neural-sparse-tokenizer-v1` has been determined to be the smallest model we can use for testing ([Documentation](https://opensearch.org/docs/latest/ml-commons-plugin/pretrained-models/#sparse-encoding-models)) , however the required fields for registering a `sparse encoding model` is different than the required fields for registering a custom `text embedding model`.

In order to replace the model used in integration testing with this sparse encoding model, it is required to separate out the `RegisterLocalModelStep` into a `RegisterCustomLocalModelStep` and `RegisterSparseEncodingLocalModelStep`. Additionally, we require support for registering an `OpenSearch -provided pretained model`, which does not require a URL. 

### What solution would you like?
The `RegisterCustomLocalModelStep` relates to the following [documentation](https://opensearch.org/docs/latest/ml-commons-plugin/api/model-apis/register-model/#register-a-custom-model) and will have the following required and optional fields : 

Required keys :
- `name`
- `version`
- `model_format`
- `function_name`
- `model_content_hash_value`
- `url`
- `model_type`
- `embedding_dimension`
- `framework_type`

Optional keys :
- `description`
- `model_group_id`
- `all_config`
- `deploy`

The `RegisterSparseEncodingModelStep` relates to the following [documentation ](https://opensearch.org/docs/latest/ml-commons-plugin/api/model-apis/register-model/#register-a-pretrained-sparse-encoding-model) and will have the following required and optional fields 

Required keys :
- `name`
- `version`
- `model_format`
- `function_name`
- `model_content_hash_value`
- `url`

Optional keys :
- `description`
- `model_group_id`
- `deploy`

The `RegisterLocalPretrainedModelStep` relates to the following [documentation](https://opensearch.org/docs/latest/ml-commons-plugin/api/model-apis/register-model/#register-a-pretrained-text-embedding-model) and will have the following required and optional fields

Required keys :
- `name`
- `version`
- `model_format`

Optional keys :
- `description`
- `model_group_id`
- `deploy`

**Comment by dbwiddis** [comment]
Suggestion:
 - rename existing `RegisterLocalModelStep` into an abstract parent step.
 - add an abstract method to get the required and optional keys 
 - create 3 subclasses implementing those required/optional keys methods, each with their own NAME
