### ISSUE TITLE
[CI] macOS Integ Test Flakiness

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/flow-framework#442]
### Is your feature request related to a problem?

Integ tests are flaky on macOS.  Given that failures have primarily been resource-constrained, and that macOS runners are really VMs and tend to ve more limiting, this is not a surprise.

### What solution would you like?

Pick one:
 - Include longer timeouts that reduce/eliminate issues with macOS tests.  We're already wating 4-6 minutes for tests to complete, adding an extra minute to avoid a "retry" that adds another 4-6 minutes is a win.
 - Use JNA `Platform` class to test whether we're on macOS and add longer time for that platform
 - Use a `bash` script in the github action to automatically retry N times.  See [this example](https://github.com/oshi/oshi/blob/01e192a28e5d267a8f360f82d830a6f5fbe48939/.github/workflows/unix.yaml#L99) from a project I maintain.  This (with 2 tries) is consistent with OpenSearch Jenkins retries.

### What alternatives have you considered?

Investigating whether macOS is officially supported and if not, using GitHub's `allow_failure: true` on macOS tests.  I don't like this option but it's the easiest.

### Do you have any additional context?

macOS is a fantastic operating system but it is specifically designed to run on Apple hardware and not in a VM.

**Comment by owaiskazi19** [comment]
How about doing something similar to core https://github.com/opensearch-project/OpenSearch/issues/2547? We can use the https://blog.gradle.org/gradle-flaky-test-retry-plugin plugin to perform the retry.

**Comment by dbwiddis** [comment]
Hey @kgantchev thanks for the idea. I've actually taken advantage of these runners on other projects I maintain.

All OpenSearch project repo settings are centrally managed so getting this app approved has to go through these organization admins.  We'd need to come up with a justification for the need to do this testing to propose adding it, but I am not sure it's really necessary here (and given the scale of this organization's projects, I doubt we'd fit under your free offering.)

our primary user base uses cloud servers on hardware optimized for that purpose (flexible storage and memory choices, no need for displays), while Apple Silicon is primarily optimized for the end user market (integrated on-chip memory and GPU).  So our investments in testing hardware/software need to focus on the overwhelming majority of users.

**Comment by kgantchev** [comment]
> I've actually taken advantage of these runners on other projects I maintain.  

Awesome! I'm glad it has come in handy.  

> ...  
> our primary user base uses cloud servers on hardware optimized for that purpose (flexible storage and memory choices, no need for displays), while Apple Silicon is primarily optimized for the end user market (integrated on-chip memory and GPU). So our investments in testing hardware/software need to focus on the overwhelming majority of users.  

Got it. Thanks for the feedback. I guess I missed the full context here. :) I appreciate it.

**Comment by dbwiddis** [comment]
Reopening this issue as the recent PRs did not fix the node drop issue (but did give much less confusing logs)

**Comment by dbwiddis** [comment]
Closing this as it's no longer macOS central, opening a new issue for multi-node.
