### ISSUE TITLE
[FEATURE] 2.13 Launch Configurable Automation templates for OpenSearch AI Use Cases

### ISSUE THREAD

**Issue by minalsha** [opensearch-project/flow-framework#541]
### Is your feature request related to a problem?
As part of 2.13 release, we are GA'ing automated templates which would help users to create a connector, register a model, deploy it, register agents, tools etc through one API call rather than doing the complex setup of calling multiple APIs and waiting for their responses.  Please see RFC: [link](https://github.com/opensearch-project/OpenSearch/issues/9213)

As part of this 2.13 release following is included:

1. Initial design of Workflow Use Case Templates
2. Implementation of basic CRUD APIs for templates and a status API
3. Implementation of DAG-based sequencing of building blocks called Workflow Steps
4. Execution of the workflow steps via provision and deprovision API
5. Implementation of WorkflowSteps supporting the use case of setting up a conversational assistant / query generator integrating with ML Commons Agent Framework using a single API call
6. Pre-defined templates and defaults [https://github.com/opensearch-project/flow-framework/issues/496](url)
7. Implement CreateSearchPipeline Workflow Step integrating with Search Pipelines [https://github.com/opensearch-project/flow-framework/issues/545](url)
8. Implement CreateIngestPipeline Workflow Step integrating with Ingest Pipelines [https://github.com/opensearch-project/flow-framework/issues/104](url)

For future/upcoming deliverables, please see our development plan/milestones: [https://github.com/opensearch-project/flow-framework/issues/475](url).

**Comment by hdhalter** [comment]
@minalsha , are there any documentation implications for 2.13? Thanks!

**Comment by dbwiddis** [comment]
> @minalsha , are there any documentation implications for 2.13? Thanks!

We'll have a few tweaks to the documentation, adding a few more optional parameters to some of the APIs.  I have one open PR but there will probably be more soon: https://github.com/opensearch-project/documentation-website/pull/6547 

Should we submit as the new features are available or wait until all are ready?

**Comment by hdhalter** [comment]
> > @minalsha , are there any documentation implications for 2.13? Thanks!
> 
> We'll have a few tweaks to the documentation, adding a few more optional parameters to some of the APIs. I have one open PR but there will probably be more soon: [opensearch-project/documentation-website#6547](https://github.com/opensearch-project/documentation-website/pull/6547)
> 
> Should we submit as the new features are available or wait until all are ready?

Awesome, thanks! I'll attach the PR to this issue for our records.

**Comment by dbwiddis** [comment]
@minalsha We've launched! I think we can close this issue?
