### ISSUE TITLE
[INVESTIGATE] Find Potential Alternatives to Jackson

### ISSUE THREAD

**Issue by amitgalitz** [opensearch-project/flow-framework#566]
### Is your feature request related to a problem?
Currently we use Jackson to map the configuration map into a string for the ingest pipeline step. The configuration map can be completely arbitrary and we just want to pass this along as a string to the create ingest or search pipeline actions. Jackson has been a root cause for a good amount of CVEs, opening this a place to comment on future options to use instead of Jackson.

**Comment by dbwiddis** [comment]
Consider `JsonB`.  I think that's what the [Opensearch Java client uses](https://github.com/opensearch-project/opensearch-java/blob/8513615054032fe5814f32c1c5424b6dc7d90d3b/java-client/src/main/java/org/opensearch/client/json/jsonb/JsonbJsonpMapper.java#L50).

https://javaee.github.io/javaee-spec/javadocs/javax/json/bind/Jsonb.html

**Comment by dbwiddis** [comment]
```groovy
implementation 'jakarta.json.bind:jakarta.json.bind-api:2.0.1'
```
```java
import jakarta.json.bind.Jsonb;
import jakarta.json.bind.JsonbBuilder;
import java.util.Map;

public class ParseUtils {
    public static String mapToJson(Map<String, Object> map) {
        try (Jsonb jsonb = JsonbBuilder.create()) {
          return jsonb.toJson(map);
        }
    }
}
```

**Comment by dbwiddis** [comment]
In the interest of completeness, I also looked at:
 - [org.json](https://www.json.org/json-en.html):  Recent CVEs. https://ossindex.sonatype.org/component/pkg:maven/org.json/json
 - [JSON.simple](https://code.google.com/archive/p/json-simple/): Last release 2012, no CVEs. https://ossindex.sonatype.org/component/pkg:maven/com.googlecode.json-simple/json-simple@1.1.1
 - [Moshi](https://github.com/square/moshi): Active development. No CVEs. https://ossindex.sonatype.org/component/pkg:maven/com.squareup.moshi/moshi
 - [GSON](https://github.com/google/gson): Last CVE 2021 https://security.snyk.io/package/maven/com.google.code.gson:gson
 - [Jackson](https://github.com/FasterXML/jackson): Recent CVE's: https://security.snyk.io/package/maven/com.fasterxml.jackson.core:jackson-databind

Among all the packages, JsonB (formerly part of Java EE), JSON.simple (old), and Moshi are the only ones without CVEs in the last 3 years.  I'd reject JSON.simple as abandonware.  Given Java client uses JsonB it's my strong preference.

**Comment by amitgalitz** [comment]
> In the interest of completeness, I also looked at:
> 
> * [org.json](https://www.json.org/json-en.html):  Recent CVEs. https://ossindex.sonatype.org/component/pkg:maven/org.json/json
> * [JSON.simple](https://code.google.com/archive/p/json-simple/): Last release 2012, no CVEs. https://ossindex.sonatype.org/component/pkg:maven/com.googlecode.json-simple/json-simple@1.1.1
> * [Moshi](https://github.com/square/moshi): Active development. No CVEs. https://ossindex.sonatype.org/component/pkg:maven/com.squareup.moshi/moshi
> * [GSON](https://github.com/google/gson): Last CVE 2021 https://security.snyk.io/package/maven/com.google.code.gson:gson
> * [Jackson](https://github.com/FasterXML/jackson): Recent CVE's: https://security.snyk.io/package/maven/com.fasterxml.jackson.core:jackson-databind
> 
> Among all the packages, JsonB (formerly part of Java EE), JSON.simple (old), and Moshi are the only ones without CVEs in the last 3 years. I'd reject JSON.simple as abandonware. Given Java client uses JsonB it's my strong preference.

Thank you for the investigation here! I'll take a look at these, I also think using a package that is used in core/clients/other plugins could help since more people will be working on addressing any problems, especially if core is just in charge of upgrading version of the package and we take it downstream

**Comment by dbwiddis** [comment]
Completed in #586
