### ISSUE TITLE
[FEATURE] Create a new Util method for a common pattern

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/flow-framework#720]
### Is your feature request related to a problem?
We have the below pattern in couple of WorkflowSteps in the codebase
```java
inputs.containsKey(foo) ? Booleans.parseBoolean(inputs.get(foo).toString()) : null
```
This can be refactored into a util method to avoid duplication.

### What solution would you like?
Create a Util method in ParseUtils.java file, have the above code in it. Invoke the util method everywhere where the above pattern is found.

### What alternatives have you considered?
Keep it as it is

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by dbwiddis** [comment]
@martinpkr can you comment on this issue so we can assign it to you?

**Comment by martinpkr** [comment]
Will do in 20-25 minutes!

**Comment by dbwiddis** [comment]
> Will do in 20-25 minutes!

You just did, haha!

**Comment by martinpkr** [comment]
Didn’t know it worked like that, awesome haha
