### ISSUE TITLE
[FEATURE] Create Integration Test framework

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/flow-framework#73]
### Is your feature request related to a problem?
Currently, the project just has unit tests for the features built until now. 

- [x] A test framework need to be implemented for developers to write integration tests. 
- [x] Run integ test on CI for every PR. https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/56

### What solution would you like?
Taking an example from ml-commons. Integtest task in build.gradle [like](https://github.com/opensearch-project/ml-commons/blob/main/plugin/build.gradle#L142)

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by dbwiddis** [comment]
We currently have an IT framework as part of the template.

This test validates that the plugin was installed.
https://github.com/opensearch-project/opensearch-ai-flow-framework/blob/main/src/test/java/org/opensearch/flowframework/FlowFrameworkPluginIT.java

That test runs with every CI.

What is currently missing?

**Comment by owaiskazi19** [comment]
Ah! I missed the framework completely @dbwiddis. Thanks for the pointer.
Also, IMO we should have a GHA to run integ test separately than our usual build CI.

**Comment by dbwiddis** [comment]
Sure, we should run them separately.

Also, the IT tests is flaky.  It often fails with a 404 error, but works on retry.
 Any idea how to fix it?

`org.opensearch.client.ResponseException: method [GET], host [http://0.0.0.0:0/], URI [/_cat/plugins], status line [HTTP/1.1 404 Not Found]`
