### ISSUE TITLE
[FEATURE] Function getToolsParametersMap in ToolStep should parse connector id

### ISSUE THREAD

**Issue by yuye-aws** [opensearch-project/flow-framework#845]
### Is your feature request related to a problem?
When creating **Connector tool** with `connector_id` from previous node inputs, connector id is missing.

### What solution would you like?
Add `connector_id` into the parsing function in ToolStep.

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by dbwiddis** [comment]
Great request, @yuye-aws .  Feel free to submit a PR.

You'd just need to add Connector ID to this line:
https://github.com/opensearch-project/flow-framework/blob/3a88199ca5cf353bbe043c4042d699fa88c34082/src/main/java/org/opensearch/flowframework/workflow/ToolStep.java#L51

**Comment by yuye-aws** [comment]
Thanks! TBH, I am new to this repo. Will submit a PR soon.

**Comment by dbwiddis** [comment]
Let us know if you need any more help!  There may be additional steps (not sure if the builder has the setter you need, etc.) but the above steps should get you started!

**Comment by yuye-aws** [comment]
Thanks. I think the connector_id is just like the model_id. I will implement this feature within function `getToolsParametersMap`.
