### ISSUE TITLE
[BUG] Compile failure with new MLTask Constructor

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/flow-framework#858]
### What is the bug?

https://github.com/opensearch-project/ml-commons/pull/2825 added a new parameter to the constructor.  We use that in a test:
> src/test/java/org/opensearch/flowframework/workflow/RegisterLocalPretrainedModelStepTests.java:140: error: no suitable constructor found for MLTask(String,String,,,MLTaskState,,,,,,,,,boolean)

### How can one reproduce the bug?

Attempt to compile the code with current upstream dependencies.

Specifically:
```bash
./gradlew compileTestJava
```
(If it passes, you probably have cached dependencies.)

### What is the expected behavior?

Code compiles.

### What is your host/environment?

Multiple environments failed in https://github.com/opensearch-project/flow-framework/issues/856 but you can probably reproduce it anywhere.

### Do you have any additional context?

The constructor is annotated `@Builder` so we should change that line of code to use a builder (omitting the nulls) to be robust to future changes.

This needs to be fixed promptly and backported to 2.17.

**Comment by junweid62** [comment]
Commenting now:)
