### ISSUE TITLE
[FEATURE] Ml-commons plugin introducing a new optional field "config" in MLTooSpec

### ISSUE THREAD

**Issue by jngz-es** [opensearch-project/flow-framework#878]
### Is your feature request related to a problem?
Ml-commons is introducing a new field `config` in `MLToolSpec` as showed in the pr https://github.com/opensearch-project/ml-commons/pull/2977. With the change, we allow cx to configure some static parameters for tools that stay unchanged/persist during the tool execution. It will fix a couple of bugs mentioned in the pr.

### What solution would you like?
The pr https://github.com/opensearch-project/ml-commons/pull/2977.

### What alternatives have you considered?
N/A.

### Do you have any additional context?
It's an optional field.

**Comment by dbwiddis** [comment]
This should be a simple change to the [`ToolStep`](https://github.com/opensearch-project/flow-framework/blob/43a9f871de50fc57758efd57c0f8899b22cecc3a/src/main/java/org/opensearch/flowframework/workflow/ToolStep.java#L51-L94) class adding the new optional parameter.
 - please also update the test case
 - please also migrate the input/output set per https://github.com/opensearch-project/flow-framework/issues/535
