### ISSUE TITLE
[BUG] errors in sample templates

### ISSUE THREAD

**Issue by yuye-aws** [opensearch-project/flow-framework#955]
### What is the bug?
I've found the sample samples in file https://github.com/opensearch-project/flow-framework/blob/main/sample-templates/alert-summary-agent-claude-tested.json is wrong.

### How can one reproduce the bug?
Provision resources with this template. Then, I call `predict` on the created claude model. I will then meet with the following error:

```
{
  "error": {
    "root_cause": [
      {
        "type": "status_exception",
        "reason": "Error from remote service: {\"message\":\"prompt must start with \\\"\\n\\nHuman:\\\" turn after an optional system prompt\"}"
      }
    ],
    "type": "status_exception",
    "reason": "Error from remote service: {\"message\":\"prompt must start with \\\"\\n\\nHuman:\\\" turn after an optional system prompt\"}"
  },
  "status": 400
}
```

### What is the expected behavior?
Both the created agent and claude model should work

### What is your host/environment?
Linux. OpenSearch 2.18.

### Do you have any screenshots?
<img width="1727" alt="image" src="https://github.com/user-attachments/assets/ce5bf859-6436-4769-8a08-1e3bb2cd06db">

### Do you have any additional context?
Need to check other templates to see whether there are any errors.

**Comment by yuye-aws** [comment]
May also need to check other dashboard assistant agents.

**Comment by dbwiddis** [comment]
https://github.com/opensearch-project/flow-framework/pull/873

@qianheng-aws can you please investigate?

**Comment by qianheng-aws** [comment]
> #873
> 
> @qianheng-aws can you please investigate?

We need to add `\n\nHuman:` at the beginning of the prompt for model claude v1. Fixed by this PR: https://github.com/opensearch-project/flow-framework/pull/958

**Comment by yuye-aws** [comment]
Find out that `anomaly-detector-suggestion-agent-claude.json` also has the same error. @gaobinlong can you update the prompt like https://github.com/opensearch-project/flow-framework/blob/b32f98bedfbab1c19c225845737c72489789f956/sample-templates/alert-summary-log-pattern-agent.json#L29?

**Comment by yuye-aws** [comment]
Also needs these 2 PRs:
1. https://github.com/opensearch-project/flow-framework/pull/959
2. https://github.com/opensearch-project/flow-framework/pull/936
